//
// Created by hugo on 28-11-24.
//

#ifndef IMPLEMENTATION_AND_EXAMPLES_PATHFOLLOWER_H
#define IMPLEMENTATION_AND_EXAMPLES_PATHFOLLOWER_H


class PathFollower {

};


#endif //IMPLEMENTATION_AND_EXAMPLES_PATHFOLLOWER_H
