//
// Created by hugo on 25-11-24.
//

#ifndef IMPLEMENTATION_AND_EXAMPLES_SIMPLEPATHPLANNER_H
#define IMPLEMENTATION_AND_EXAMPLES_SIMPLEPATHPLANNER_H


class SimplePathPlanner {

};


#endif //IMPLEMENTATION_AND_EXAMPLES_SIMPLEPATHPLANNER_H
